### ISSUE TITLE
How to fix "FloatingPointError: divide by zero encountered in true_divide" ?

### ISSUE THREAD

**Issue by chenghancc** [SsGood/DBGAN#1]
When I use DBGAN model for Link prediction, the following error occurs：

Traceback (most recent call last):
  File "C:/Users/Monarch/Desktop/DBGAN-master/DBGAN_link/run.py", line 14, in <module>
    runner.erun()
  File "C:\Users\Monarch\Desktop\DBGAN-master\DBGAN_link\link_prediction.py", line 43, in erun
    DPP.sample_exact_k_dpp(size=0)
  File "D:\Users\Monarch\Anaconda3\envs\tf1\lib\site-packages\dppy\finite_dpps.py", line 506, in sample_exact_k_dpp
    random_state=rng)
  File "D:\Users\Monarch\Anaconda3\envs\tf1\lib\site-packages\dppy\finite_dpps.py", line 492, in sample_exact_k_dpp
    self.L_eig_vals = self.K_eig_vals / (1.0 - self.K_eig_vals)
FloatingPointError: divide by zero encountered in true_divide

Process finished with exit code 1

How to solve this problem ？

**Comment by SsGood** [comment]
Plz check the dppy version is 0.2.0 or not. If the version of dppy is correct while the problem still  appear,  you could also achieve the k-dpp sampling by another package, pydpp.

**Comment by Monarch-CH** [comment]
> 请检查 dppy 版本是否为 0.2.0。如果 dppy 的版本是正确的，但问题仍然存在，您也可以通过另一个包 pydpp 实现 k-dpp 采样。

Yes, the version of the dppy I use is 0.2.0. I will try pydpp. Thank you for your reply.

**Comment by chenghancc** [comment]
> Plz check the dppy version is 0.2.0 or not. If the version of dppy is correct while the problem still appear, you could also achieve the k-dpp sampling by another package, pydpp.

Yes, the version of the dppy I use is 0.2.0. I will try pydpp. Thank you for your reply.

**Comment by chenghancc** [comment]
> > Plz check the dppy version is 0.2.0 or not. If the version of dppy is correct while the problem still appear, you could also achieve the k-dpp sampling by another package, pydpp.
> 
> Yes, the version of the dppy I use is 0.2.0. I will try pydpp. Thank you for your reply.

When I change dppy to pydpp the code works, thanks a lot！
